WebForShaniu/WebForShaniu/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from . import view, Main

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', view.Main),
    url(r'^R|r/', view.EntryR),
    url(r'^CheckPassword', Main.CheckPassword),
    url(r'^Travel', view.Travel),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^suzhou', view.suzhou),
]

WebForShaniu/blog/urls.py
from django.conf.urls import url

from . import views

app_name ='blog'
urlpatterns = [
    url(r'^blog$', views.index, name = "index"),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name="archives"),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

WebForShaniu/comments/urls.py
#coding=utf-8

from django.conf.urls import url

from . import views

app_name = "comments"

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name = 'post_comment'),
]

WebForShaniu/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 100)

class Tag(models.Model):
    name = models.CharField(max_length = 100)

class Post(models.Model):
    title = models.CharField(max_length = 100)
    body = models.TextField()
    create_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length = 800, blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)
    viewnum = models.PositiveIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-create_time', 'title']

    def increase_viewnum(self):
       self.viewnum += 1
       self.save(update_fields=['viewnum'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        super(Post, self).save(*args, **kwargs)

WebForShaniu/comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

WebForShaniu/comments/forms.py
#coding=utf-8

from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

WebForShaniu/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from .models import Post, Category, Tag
from django.shortcuts import get_object_or_404
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView

# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-create_time')
    return render(request, 'blog/index.html', context={
        'title' : 'Our Blog',
        'welcome' : 'Welcome to our blog!',
        'post_list' : post_list,
    })

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    post.increase_viewnum()

    post.body = markdown.markdown(post.body,
                                  extensions = [
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    comment_list = post.comment_set.all()

    return render(request, 'blog/detail.html', context = {'post' : post,
                                                          'form' : form,
                                                          'comment_list' : comment_list,})

def archives(request, year, month):
    post_list = Post.objects.filter(create_time__year = year,
                                    create_time__month = month,
                                    ).order_by('-create_time')
    return render(request, 'blog/index.html', context={
                                            'title' : 'Our Blog',
                                            'post_list' : post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk = pk)
    post_list = Post.objects.filter(category = cate).order_by('-create_time')
    return render(request, 'blog/index.html', context = {
                                            'title' : 'Our Blog',
                                            'post_list' : post_list})

class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

WebForShaniu/comments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm

# Create your views here.
def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk = post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            context = {'post' : post,
                       'form' : form,
                       'comment_list' : comment_list,}
            return render(request, 'blog/detail.html', context=context)
    return redirect(post)

WebForShaniu/templates/Main.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>WebForDaxiaojie</title>
</head>
<body>
    <form action="/CheckPassword" method="post">
        {% csrf_token %}
        <input type="text" name="Password">
        <input type="submit" value="Submit">
    </form>
    <P>{{ rlt }}</p>
<iframe src="//www.seniverse.com/weather/weather.aspx?uid=UD1CBEABFD&cid=CHBJ000100&l=zh-CHS&p=SMART&a=0&u=C&s=3&m=0&x=1&d=3&fc=&bgc=&bc=&ti=0&in=0&li=" frameborder="0" scrolling="no" width="500" height="110" allowTransparency="true"></iframe>
<iframe src="//www.seniverse.com/weather/weather.aspx?uid=UD1CBEABFD&cid=CHSH001100&l=zh-CHS&p=SMART&a=0&u=C&s=3&m=0&x=1&d=3&fc=&bgc=&bc=&ti=0&in=0&li=" frameborder="0" scrolling="no" width="500" height="110" allowTransparency="true"></iframe>
<iframe src="//www.seniverse.com/weather/weather.aspx?uid=UD1CBEABFD&cid=CHSD060000&l=zh-CHS&p=SMART&a=0&u=C&s=3&m=0&x=1&d=3&fc=&bgc=&bc=&ti=0&in=0&li=" frameborder="0" scrolling="no" width="500" height="110" allowTransparency="true"></iframe>
<iframe src="//www.seniverse.com/weather/weather.aspx?uid=UD1CBEABFD&cid=CHJS060400&l=zh-CHS&p=SMART&a=0&u=C&s=3&m=0&x=1&d=3&fc=&bgc=&bc=&ti=0&in=0&li=" frameborder="0" scrolling="no" width="500" height="110" allowTransparency="true"></iframe>
<iframe src="//www.seniverse.com/weather/weather.aspx?uid=UD1CBEABFD&cid=CHJS030000&l=zh-CHS&p=SMART&a=0&u=C&s=3&m=0&x=1&d=3&fc=&bgc=&bc=&ti=0&in=0&li=" frameborder="0" scrolling="no" width="500" height="110" allowTransparency="true"></iframe>
</body>
</html>

WebForShaniu/templates/Second.html
<!DCOTYPE html>
<html>
<head>
<title>WebForShaniu</title>
<a href="http://shaniu.site/Travel" target="_parent">Travel</a>
<a href="http://shaniu.site/R" target="_parent">R</a>
</head>
</html>

WebForShaniu/templates/Travel.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		body, html {width: 100%;height: 100%;margin:0;font-family:"微软雅黑";}
		#allmap{width:100%;height:500px;}
		p{margin-left:5px; font-size:14px;}
	</style>
	<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=aRpARkvGAmm4KFkGcN0MjTo3RmfeLxSE"></script>
	<script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>
	<title>Our Travel</title>
</head>
<body>
	<div id="allmap"></div>
	<p>TODO Add picture or other</p>
</body>
</html>
<script type="text/javascript">
	// 百度地图API功能	
	map = new BMap.Map("allmap");
	map.centerAndZoom(new BMap.Point(116.338897,40.011006), 5);
        map.addControl(new BMap.NavigationControl());
	var data_info = [[110.098586,34.516553,"2013年8月 西安"],[121.593023,38.902386,"2015年6月 大连"],[100.17057,36.91101,"2013年8月 青海湖"],[105.37548, 36.168235, "2013年7月 新塬"],[118.731268, 32.014363, "2016年5月 南京"], [120.265028,33.51415,"特庸"],[116.59575,35.418399,"济宁"]];
	var opts = {
				width : 250,     // 信息窗口宽度
				height: 80,     // 信息窗口高度
				title : "足迹" , // 信息窗口标题
				enableMessage:true//设置允许信息窗发送短息
			   };
	for(var i=0;i<data_info.length;i++){
		var marker = new BMap.Marker(new BMap.Point(data_info[i][0],data_info[i][1]));  // 创建标注
		var content = data_info[i][2];
		map.addOverlay(marker);               // 将标注添加到地图中
		addClickHandler(content,marker);
	}
	function addClickHandler(content,marker){
		marker.addEventListener("click",function(e){
			openInfo(content,e)}
		);
	}
	function openInfo(content,e){
		var p = e.target;
		var point = new BMap.Point(p.getPosition().lng, p.getPosition().lat);
		var infoWindow = new BMap.InfoWindow(content,opts);  // 创建信息窗口对象 
		map.openInfoWindow(infoWindow,point); //开启信息窗口
	}
</script>

WebForShaniu/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-10 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Daxiaojie</b> &amp; Daguanjia</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{%url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<!--
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>
-->
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        Waiting Publish
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year}}.{{ date.month}}</a>
                        </li>
                        {% empty %}
                        Waiting Publish
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                                <span class="post-count">{{ category.post_set.count }}</span></a>
                        </li>
                        {% empty %}
                        Waiting Publish
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        Waiting publish
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<!--
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>
-->
<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

WebForShaniu/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <artice class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-time"
                                                          datetime="{{ post.create_time}}">
                    {{ post.create_time }}
                </time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-linl"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.viewnum }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
            <div class="widget-tag-cloud">
                <ul>
                    {% for tag in post.tags.all %}
                    <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </artice>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}">Name</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">URL:</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">Comment:</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">Commit</button>
            </div>
        </form>
        <div class="comment-list-panel" id="">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.create_time }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                Waitting Publish
                {% endfor %}
            </ul>
        </div>
    </section>
    <!--
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
    -->
{% endblock main %}

WebForShaniu/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00"></time></a></span>
                    <span class="post-author"><a href="#">{{ post.author}} </a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.viewnum }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}...</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolue_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">Waiting our blog!</div>
    {% endfor %}

    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <!--
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
    -->
{% endblock main %}

WebForShaniu/templates/suzhou.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		body, html {width: 100%;height: 100%;margin:0;font-family:"微软雅黑";}
		#allmap{width:100%;height:100%;}
		p{margin-left:5px; font-size:14px;}
	</style>
	<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=aRpARkvGAmm4KFkGcN0MjTo3RmfeLxSE"></script>
	<script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>
	<title>SuZhou Travel</title>
</head>
<body>
	<div id="allmap"></div>
</body>
</html>
<script type="text/javascript">
	// 百度地图API功能
	map = new BMap.Map("allmap");
	map.centerAndZoom(new BMap.Point(120.599387,31.383376), 5);//Point of hotel
	var data_info = [[120.48745,31.300943,"天池山"],[120.635263,31.326931,"狮子林"],
	[120.59896,31.32176,"留园"],[120.634121,31.329144,"苏州博物馆"],[120.635703,31.330247,"拙政园"],
	[120.640254,31.303709,"网师园"],[120.515708,30.921256,"震泽古镇"],[120.588083,31.34068,"虎丘"],
	[120.632066,31.300634,"沧浪亭"],[120.574907,31.316454,"寒山寺"],[120.855935,31.119287,"周庄"],
	[120.725441,31.163773,"同里"],[120.627424,31.303623,"书院巷"],[120.609802,31.322674,"山塘街"]
	,[120.615319,31.31924,"艺圃"]];
	var opts = {
				width : 250,     // 信息窗口宽度
				height: 80,     // 信息窗口高度
				title : "View" , // 信息窗口标题
				enableMessage:true//设置允许信息窗发送短息
			   };

	for(var i=0;i<data_info.length;i++){
		var point = new BMap.Point(data_info[i][0],data_info[i][1]);
	    var marker = new BMap.Marker(point);  // 创建标注
	    map.addOverlay(marker);              // 将标注添加到地图中
	    var content = data_info[i][2];
	    addClickHandler(content,marker);
	}

	function addClickHandler(content,marker){
		marker.addEventListener("click",function(e){
			openInfo(content,e)}
		);
	}
	function openInfo(content,e){
		var p = e.target;
		var point = new BMap.Point(p.getPosition().lng, p.getPosition().lat);
		var infoWindow = new BMap.InfoWindow(content,opts);  // 创建信息窗口对象
		map.openInfoWindow(infoWindow,point); //开启信息窗口
	}

	var data_info = [[120.6319,31.316697,"松鹤楼菜馆(观前街店)"],[120.640255,31.31881,"松鹤楼菜馆(平江路店)"],
	[120.609838,31.316172,"松鹤楼菜馆(茉莉花店)"],[120.607737,31.324771,"松鹤楼菜馆(山塘街店)"],[120.631902,31.31634,"得月楼观前店"],
	[120.699408,31.308638,"得月楼(李公堤店)"],[120.69549,31.308497,"洋洋中餐馆园区店"],[120.609568,31.322797,"赵元章肉骨烧"],
	[120.631345,31.315771,"桃花源记(观前店)"],[120.640283,31.320537,"桃花源记"],[120.63546,31.321558,"藏书羊肉"],
	[120.740416,31.330122,"金海华赫本时光"],[120.634882,31.321206,"哑巴生煎"],[120.641114,31.317511,"鸡脚旮旯"],
	[120.67371,31.320963,"鸡脚旮旯"],[120.63924,31.324684,"狐狸家手工酸奶酪"],[120.640947,31.317889,"狐狸家手工酸奶酪(平江路二店)"],
	[120.6311,31.310025,"祥鑫饮食店"],[120.632204,31.315998,"珍珠饭店"],];
	for(var i=0;i<data_info.length;i++){
		var point = new BMap.Point(data_info[i][0],data_info[i][1]);
	    var marker = new BMap.Marker(point);  // 创建标注
	    map.addOverlay(marker);              // 将标注添加到地图中
        var label = new BMap.Label(data_info[i][2],{offset:new BMap.Size(20, -10)});
        marker.setLabel(label);

	}
	var navigationControl = new BMap.NavigationControl({
    // 靠左上角位置
    anchor: BMAP_ANCHOR_TOP_LEFT,
    // LARGE类型
    type: BMAP_NAVIGATION_CONTROL_LARGE,
    // 启用显示定位
    enableGeolocation: true
  });
  map.addControl(navigationControl);
  // 添加定位控件
  var geolocationControl = new BMap.GeolocationControl();
  geolocationControl.addEventListener("locationSuccess", function(e){
    // 定位成功事件
    var address = '';
    address += e.addressComponent.province;
    address += e.addressComponent.city;
    address += e.addressComponent.district;
    address += e.addressComponent.street;
    address += e.addressComponent.streetNumber;
    alert("当前定位地址为：" + address);
  });
  geolocationControl.addEventListener("locationError",function(e){
    // 定位失败事件
    alert(e.message);
  });
  map.addControl(geolocationControl);
</script>